### ISSUE TITLE
Add support for fixture test output to message sink

### ISSUE THREAD

**Issue by gitfool** [trbenning/serilog-sinks-xunit#18]
Fixtures have different lifetimes compared to tests and can use the diagnostic message sink:
- [Capturing output in extensibility classes](https://xunit.net/docs/capturing-output#output-in-extensions)
- https://github.com/xunit/xunit/pull/1705

**Comment by trbenning** [comment]
It looks like the NuGet package didn't get created for some reason. I'm looking into it now.

**Comment by gitfool** [comment]
Okay. Let me know if I can help.
