### ISSUE TITLE
Build #2.0.2 did not create a NuGet package.

### ISSUE THREAD

**Issue by trbenning** [trbenning/serilog-sinks-xunit#20]
https://dev.azure.com/benning/Serilog.Sinks.XUnit/_build/results?buildId=47&view=results

**Comment by trbenning** [comment]
@gitfool Here's the issue for the failed NuGet package, FYI

**Comment by gitfool** [comment]
@trbenning found the issue. I submit another PR.

**Comment by trbenning** [comment]
Lol, I just found it as well. The `IsPackable` attribute in the csproj?

**Comment by gitfool** [comment]
Yep. I'd also add that (with false) and `IsTestable` (true) to the test project.

**Comment by gitfool** [comment]
Are you going to fix or do you want me to?

**Comment by trbenning** [comment]
Looks like that fixed it. Thanks again!
