### ISSUE TITLE
How about changing the DefaultConsoleOutputTemplate 

### ISSUE THREAD

**Issue by hhko** [trbenning/serilog-sinks-xunit#24]
The **DefaultConsoleOutputTemplate** in serilog-sinks-xunit is `"{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level}] {Message}{NewLine}{Exception}"`.
- https://github.com/trbenning/serilog-sinks-xunit/blob/master/src/Serilog.Sinks.XUnit/XUnitLoggerConfigurationExtensions.cs#L17
 
It is different from serilog.
The DefaultConsoleOutputTemplate  of serilog is `"[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}"`.

**Comment by gitfool** [comment]
@trbenning FWIW, I think this would be a much better default too. It aligns with the well known console default that has a fixed length prefix before the message, regardless of the log level, which makes the log much more readable. Also the year-month-day is just noise in test logs. Hopefully you agree so I sent a PR. 😉
